### ISSUE TITLE
MN -> PDF: Lowercase letter shown in cross-reference text

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#100]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

There are cases where a cross-reference text is show lowercase letter instead of uppercase.
This seems to happen when such cross-reference is placed at the beginning of the line.

*From iso-10667-2*:
![issue1-generated](https://user-images.githubusercontent.com/33627611/135786357-f454cda6-8dad-48b0-a061-bc210ed582be.PNG)

Original:
![issue1-original](https://user-images.githubusercontent.com/33627611/135786368-446e3eea-6b4f-4305-be2d-1773f75e875c.PNG)

**Comment by Intelligent2013** [comment]
The issue in generated metanorma xml.

adoc:
```adoc
NOTE: <<sec_A.3>> provides a list of rights and responsibilities for the {{assessment}} participant.
...
[[sec_A.3]]
=== ​Assessment participants' responsibilities
```

Generated metanorma xml:
```xml
<note id="_">
	<name>NOTE  1</name>
	<p id="_">
		<xref target="sec_A.3">
			<strong>a.3</strong>
		</xref> provides a list of rights and responsibilities for the assessment participant.</p>
</note>
```

**Comment by Intelligent2013** [comment]
Fixed. Metanorma generates correct xml now:
![image](https://user-images.githubusercontent.com/5559926/141611510-556f3208-8beb-4b51-8341-77547bc19c26.png)
