### ISSUE TITLE
Update to Apache FOP 2.7

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#112]
Apache FOP Version 2.7 (20 Jan 2022), https://xmlgraphics.apache.org/fop/2.7/changes_2.7.html
To do:
- [x] update dependency in pom.xml
- [x] update Apache FOP java classes included in mn2pdf
- [x] testing resulted PDFs

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 . is there any feature we can take advantage in 2.7?

**Comment by Intelligent2013** [comment]
> Thanks @Intelligent2013 . is there any feature we can take advantage in 2.7?

@ronaldtse no new features added in 2.7, but one issue fixed that can be potentially occur for PAS two-columns documents:
```
FOP-3027: Sections of text sometimes lost with span=all multiple columns
```
(https://issues.apache.org/jira/browse/FOP-3027)
Example from FOP-3027 - sections between 8 and 11 are missing:
![image](https://user-images.githubusercontent.com/5559926/151693316-9fd0bf46-be14-431d-bf78-c0291cbad0e6.png)

**Comment by Intelligent2013** [comment]
Done.
