### ISSUE TITLE
Change default fonts from Adobe Source Sans/Serif/Code to Noto Sans/Serif/Sans Mono

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf#119]
As we discovered in https://github.com/metanorma/metanorma-iso/issues/634 , Adobe Source Sans/Serif lacks a number of glyphs that severely diminish its value for being our backstop of "all fonts".

Noto however seems to have a very complete and comprehensive collection of glyphs that can serve as our backstop font.

* [Fontist formula for Noto sans mono](https://github.com/fontist/formulas/blob/v3/Formulas/google/noto_sans_mono.yml)
* [Fontist formula for Noto sans](https://github.com/fontist/formulas/blob/v3/Formulas/google/noto_sans.yml)
* [Fontist formula for Noto serif](https://github.com/fontist/formulas/blob/v3/Formulas/google/noto_serif.yml)

This task is to switch mn-native-pdf to use Noto instead of Adobe Source.

For Noto CJK and Adobe Source Han, the fonts are identical.

We need a way to package Noto in a way that is reasonable like this: https://github.com/fontist/source-fonts/releases/tag/v1.0

**Comment by ronaldtse** [comment]
The relevant line is this:
https://github.com/metanorma/mn2pdf/blob/9704241cb6473f55dac25dd7d3f3c5824c1808fe/src/main/resources/app.properties#L1

We need to support these fonts instead of Adobe Source:
* Noto CJK "Variable OTC" https://github.com/fontist/formulas/issues/129 as a replacement for Adobe Source Han
* [Fontist formula for Noto sans mono](https://github.com/fontist/formulas/blob/v3/Formulas/google/noto_sans_mono.yml) as a replacement for Adobe Source Code
* [Fontist formula for Noto sans](https://github.com/fontist/formulas/blob/v3/Formulas/google/noto_sans.yml) as a replacement for Adobe Source Sans
* [Fontist formula for Noto serif](https://github.com/fontist/formulas/blob/v3/Formulas/google/noto_serif.yml) as a replacement for Adobe Source Pro

**Comment by ronaldtse** [comment]
@Intelligent2013 I've created a package for Noto, can you use this?
https://github.com/fontist/noto-fonts/releases/tag/v1.0

* [noto-fonts-cjk-1.0.zip](https://github.com/fontist/noto-fonts/releases/download/v1.0/noto-fonts-cjk-1.0.zip)
* [noto-fonts-latn-1.0.zip](https://github.com/fontist/noto-fonts/releases/download/v1.0/noto-fonts-latn-1.0.zip)

You will need to update the font names used as backstop to match these new fonts, too.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !

**Comment by ronaldtse** [comment]
I found another benefit of using Noto which is size optimization. Noto CJK is 70MB with Sans+Serif+Mono, but Adobe Source CJK is 146MB with the same font styles. Noto will be a lot more complete given the same size boundaries as we have now.

**Comment by Intelligent2013** [comment]
- TTC font NotoSansCJK-VF.ttf.ttc  contains 5 sub-fonts:
![image](https://user-images.githubusercontent.com/5559926/165803950-20edccdc-f5ae-4cde-a347-cf9454202b7b.png)

- TTC font NotoSerifCJK-VF.ttf.ttc 
![image](https://user-images.githubusercontent.com/5559926/165804209-fb162c5a-ee9f-493d-b0e2-014ed86ce248.png)

In Apache FOP config we have to specify such entries:
```xml
<font kerning="yes" embed-url="NotoSansCJK-VF.ttf.ttc" sub-font="Noto Sans CJK JP" mn_default="true">
	<font-triplet name="Noto Sans CJK JP" style="normal" weight="normal"/>
</font>
<font kerning="yes" embed-url="NotoSansCJK-VF.ttf.ttc" sub-font="Noto Sans CJK JP" simulate-style="true" mn_default="true">
	<font-triplet name="Noto Sans CJK JP" style="italic" weight="normal"/>
</font>
<font kerning="yes" embed-url="NotoSansCJK-VF.ttf.ttc" sub-font="Noto Sans CJK JP" simulate-style="true" mn_default="true">
	<font-triplet name="Noto Sans CJK JP" style="italic" weight="bold"/>
</font>
<font kerning="yes" embed-url="NotoSansCJK-VF.ttf.ttc" sub-font="Noto Sans CJK JP" simulate-style="true" mn_default="true">
	<font-triplet name="Noto Sans CJK JP" style="normal" weight="bold"/>
</font>
```
for each sub-font.

**Comment by Intelligent2013** [comment]
> For Noto CJK and Adobe Source Han, the fonts are identical.

@ronaldtse currently, we use 'Source Han' font in normal (SourceHanSans-Normal.ttc) and bold (SourceSansPro-Bold.ttf) styles.
Why: if we don't have some bold/italic font, then Apache FOP allows to use `simulate-style` feature that allows to draw 'in memory' bold/italic style from normal font. BUT `simulate-style` feature to  bold font generation from _big_ normal font (>5-10mb) causes issues in FOP (Adobe Reader shows error on PDF opening). Therefore we need to specify physical concrete file for bold font.
For italic or bold+italic font, `simulate-style` works well.

Here is current Apache FOP font config:
```
<font kerning="yes" embed-url="SourceHanSans-Normal.ttc" sub-font="Source Han Sans Normal" mn_default="true">
	<font-triplet name="Source Han Sans" style="normal" weight="normal"/>
</font>
<font kerning="yes" embed-url="SourceHanSans-Normal.ttc" sub-font="Source Han Sans Normal" simulate-style="true" mn_default="true">
	<font-triplet name="Source Han Sans" style="italic" weight="normal"/>
</font>
<font kerning="yes" embed-url="SourceHanSans-Normal.ttc" sub-font="Source Han Sans Normal" simulate-style="true" mn_default="true">
	<font-triplet name="Source Han Sans" style="italic" weight="bold"/>
</font>
<font kerning="yes" embed-url="SourceHanSans-Bold.ttc" sub-font="Source Han Sans Bold" mn_default="true">
	<font-triplet name="Source Han Sans" style="normal" weight="bold"/>
</font>
```
and you can see that `SourceHanSans-Bold.ttc` is using for `style="normal" weight="bold"`.

I.e. ideally we need 4 fonts: normal, bold, italic, bold+italic. But if some font is missing, then we can turn-on simulate-style feature. But it doesn't work well for big fonts.

I propose don't change Source Han to Noto CJK (34-59Mb).

**Comment by ronaldtse** [comment]
> Why: if we don't have some bold/italic font, then Apache FOP allows to use simulate-style feature

@Intelligent2013 doesn't Noto Sans CJK already contain all the styles?

<img width="394" alt="Screenshot 2022-04-29 at 7 01 48 AM" src="https://user-images.githubusercontent.com/11865/165861425-3ce0f00c-f86a-4b7e-9cbd-3c5b09e7996a.png">

**Comment by ronaldtse** [comment]
> In Apache FOP config we have to specify such entries:

We can make all the fonts available?

**Comment by Intelligent2013** [comment]
> doesn't Noto Sans CJK already contain all the styles?

@ronaldtse to make sure that we see at the same font, noto-fonts-cjk-1.0.zip/NotoSansCJK-VF.ttf.ttc:
Fontforge proposes to choose these fonts:
![Uploading image.png…]()

What is file do you open?

**Comment by Intelligent2013** [comment]
> >    In Apache FOP config we have to specify such entries:

> We can make all the fonts available?

Yes, we can make available both Source and Noto families fonts. Will do so.

**Comment by ronaldtse** [comment]
The TTC contains all the 5 fonts, and all the styles are available for every font. I’ll show you a screenshot when I’m back at a computer.

**Comment by Intelligent2013** [comment]
I've just download 06_NotoSansCJKjp.zip from https://github.com/googlefonts/noto-cjk/releases/tag/Sans2.004:
- NotoSansCJKjp-Black.otf
- NotoSansCJKjp-Bold.otf
- NotoSansCJKjp-DemiLight.otf
- NotoSansCJKjp-Light.otf
- NotoSansCJKjp-Medium.otf
- NotoSansCJKjp-Regular.otf
- NotoSansCJKjp-Thin.otf

just for checking. The total size is ~110Mb. 7 font faces for _JP_

I don't sure that NotoSansCJK-VF.ttf.ttc  (36Mb) contains 5 languages and all font faces....

**Comment by Intelligent2013** [comment]
It seems there is a confusion between the concepts 'default fonts' and `backstop fonts`.
Just for note:
1. When default fonts are using (Source...Code or Noto):
 mn2pdf called without fontist manifest file or fontist didn't install specified font (user didn't agree with the license, missing font in fontist, etc.), and mn2pdf can't find font in OS system path and `{userdir}/.metanorma/fonts`, for instance:
        
    - the font 'Azo Sans' is using in CSA xslt, fontist didn't install this font. In this case, mn2pdf will replace 'Azo Sans' family fonts (regular, bold, italic, bold+italic) to 'SourceSansPro' family fonts (download fonts by `URL.sourcefonts` from app.properties, unpack them, add entries into Apache FOP fonts config).

These actions allow to produce PDF successfully even the fonts specified in XSLT didn't installed by some reason.

2. What doing Apache FOP when some glyph in missing in the font:
Each xslt contains the attribute `fo:root/@font-family`, for instance ISO xslt:
```xml
<fo:root ... font-family="Cambria, Times New Roman, Cambria Math, Source Han Sans"...
```
For each character FOP tries to find glyph in the 1st font from font-family, for instance Cambria. If glyph isn't found, then tries to find glyph in the 2nd font, etc. If glyph can't be found at all, then FOP put `#` and prints warning into the log.

Note: there are particulars, see Font Selection Strategies' section in https://xmlgraphics.apache.org/fop/2.5/fonts.html#selection for case when char is part of word, not a standalone char.

When we want to expand the font list where the FOP will find glyphs, then we need:
_first approach_:
- add font into xslt like this:
```xml
<fo:root ... font-family="Cambria, Times New Roman, Cambria Math, Source Han Sans, Noto Sans"...
```
- add font into metanorma gem (for instance, `metanorma-iso/lib/metanorma/iso/processor.rb`):
```ruby
      def fonts_manifest
        {
          "Cambria" => nil,
          "Cambria Math" => nil,
          "Times New Roman" => nil,
          "Source Han Sans" => nil,
          "Source Han Sans Normal" => nil,
          "Courier New" => nil,
          "Noto Sans" => nil,
        }
      end
```

_second approach_:
- add `:fonts: Noto Sans` into document.adoc. In this case fontist will install the font 'Noto Sans' and xslt add it into themself automatically.

**Comment by ronaldtse** [comment]
We want to change both the default font and the backstop font to Noto (away from Source), because it supports more glyphs (and is smaller in size). So we need the first approach.

**Comment by Intelligent2013** [comment]
> The TTC contains all the 5 fonts, and all the styles are available for every font. I’ll show you a screenshot when I’m back at a computer.

@ronaldtse I've checked these TTC in my MacOS VM and also see all styles. Will investigate how Apache FOP can have access to the 2nd level sub-fonts.

**Comment by Intelligent2013** [comment]
`sub-font="Noto Sans CJK JP Bold"`:
```xml
<font embed-url="file:/C:/Users/test/.metanorma/fonts/NotoSansCJK-VF.ttf.ttc" kerning="yes" mn_default="true" sub-font="Noto Sans CJK JP Bold">
	<font-triplet name="Noto Sans CJK JP" style="normal" weight="bold"/>
</font>
```
throws exception
```
Caused by: java.lang.RuntimeException: Failed to read font file file:/C:/Users/test/.metanorma/fonts/NotoSansCJK-VF.ttf.ttc
...
Caused by: java.io.IOException: Name does not exist in the TrueType collection: Noto Sans CJK JP Bold
```
because in this ttc font there are 5 sub-fonts:
- Noto Sans CJK JP
- Noto Sans CJK KR
...

Bold, Italic, etc. are something another thing...

**Comment by Intelligent2013** [comment]
`NotoSansCJK-VF.ttf.ttc` is the Variable Font (VF) (https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide). It seems Apache FOP doesn't support OpenType Variable fonts yet (https://xmlgraphics.apache.org/fop/2.7/fonts.html#custom).

I've tried the static font 'NotoSansCJK-Regular.ttc ' from [All Static Language Specific OTCs](https://github.com/googlefonts/noto-cjk/releases/download/Sans2.004/03_NotoSansCJK-OTC.zip):
```xml
<font embed-url="file:/C:/Users/test/.metanorma/fonts/NotoSansCJK-Regular.ttc" kerning="yes" sub-font="Noto Sans CJK JP">
	<font-triplet name="Noto Sans CJK JP" style="normal" weight="normal"/>
</font>
```
Apache FOP ends with errors:
```

SEVERE: Failed to read font file file:/C:/Users/test/.metanorma/fonts/NotoSansCJK-Regular.ttc
java.io.IOException: 'loca' table not found, happens when the font file doesn't contain TrueType outlines (trying to read an OpenType CFF font maybe?)
        at org.apache.fop.fonts.truetype.TTFFile.readIndexToLocation(TTFFile.java:180)
...
SEVERE: Exception
org.apache.fop.apps.FOPException: Failed to read font file file:/C:/Users/test/.metanorma/fonts/NotoSansCJK-Regular.ttc
java.lang.RuntimeException: Failed to read font file file:/C:/Users/test/.metanorma/fonts/NotoSansCJK-Regular.ttc
...
        at org.apache.fop.cli.Main.main(Main.java:214)
Caused by: java.lang.RuntimeException: Failed to read font file file:/C:/Users/test/.metanorma/fonts/NotoSansCJK-Regular.ttc
        at org.apache.fop.fonts.LazyFont.load(LazyFont.java:132)
        at org.apache.fop.fonts.LazyFont.getAscender(LazyFont.java:235)
   
...
Caused by: java.io.IOException: 'loca' table not found, happens when the font file doesn't contain TrueType outlines (trying to read an OpenType CFF font maybe?
)
        at org.apache.fop.fonts.truetype.TTFFile.readIndexToLocation(TTFFile.java:180)
        at org.apache.fop.fonts.truetype.TTFFile.updateBBoxAndOffset(TTFFile.java:169)
        at org.apache.fop.fonts.truetype.OpenFont.readFont(OpenFont.java:853)
```

**Comment by ronaldtse** [comment]
Good find indeed, I guess the Variable Font is not supported. In any case, we should still change to Noto. The different language variations is due to these regions use slightly different renditions of the same characters, but I believe they have the exact same number of glyphs. Users should be able to choose among them.

**Comment by Intelligent2013** [comment]
**Summary for Sans fonts** from https://github.com/googlefonts/noto-cjk/releases/tag/Sans2.004:
- FOP doesn't support 'Variable' fonts
- [All Static Language Specific OTCs](https://github.com/googlefonts/noto-cjk/releases/download/Sans2.004/03_NotoSansCJK-OTC.zip) causes error:
```
java.io.IOException: 'loca' table not found, happens when the font file doesn't contain TrueType outlines (trying to read an OpenType CFF font maybe?)
        at org.apache.fop.fonts.truetype.TTFFile.readIndexToLocation(TTFFile.java:180)
```
- [All Static Language Specific OTFs](https://github.com/googlefonts/noto-cjk/releases/download/Sans2.004/04_NotoSansCJK-OTF.zip) contains 35 .otf file, total size is 550Mb (unpacked). Apache FOP support them. 

- [Language Specific Monospace OTFs Japanese (日本語)](https://github.com/googlefonts/noto-cjk/releases/download/Sans2.004/11_NotoSansMonoCJKjp.zip) contains two fonts `NotoSansMonoCJKjp-Regular.otf` and `NotoSansMonoCJKjp-Bold.otf`. Apache FOP supports them. File size - 16 mb each.

- [Region Specific Subset OTFs Japanese (日本語)](https://github.com/googlefonts/noto-cjk/releases/download/Sans2.004/16_NotoSansJP.zip) contains 7 fonts - Regular, Bold, Black, Light, etc. Apache FOP supports them. Total size is 31Mb.


**Summary for Serif fonts** from: https://github.com/googlefonts/noto-cjk/releases/tag/Serif2.001:
- [Static Super OTC](https://github.com/googlefonts/noto-cjk/releases/download/Serif2.001/01_NotoSerifCJK.ttc.zip) contains one font file with all fonts and styles:
![image](https://user-images.githubusercontent.com/5559926/166910642-110d3c1a-2785-4774-8e18-14a788332dd1.png)
![image](https://user-images.githubusercontent.com/5559926/166910698-70a3630f-7da5-45b8-bed8-5760831e0e04.png)
![image](https://user-images.githubusercontent.com/5559926/166910735-0846e9bf-0804-4fb6-a35d-7aff429f065c.png)

Apache doesn't support it:
```
SEVERE: Failed to read font file file:/C:/Users/testuser/.metanorma/fonts/NotoSerifCJK.ttc 'loca' table not found, happens when the font file doesn't contain TrueType outlines (trying to read an OpenType CFF font maybe?)
java.io.IOException: 'loca' table not found, happens when the font file doesn't contain TrueType outlines (trying to read an OpenType CFF font maybe?)
```

- [All Static Language Specific OTFs](https://github.com/googlefonts/noto-cjk/releases/download/Serif2.001/05_NotoSerifCJKOTF.zip) - contains 35 font files, total unpacked size is 804mb. Apache support them.

- [Region Specific Subset OTFs Japanese (日本語)](https://github.com/googlefonts/noto-cjk/releases/download/Serif2.001/12_NotoSerifJP.zip) contains 7 styles fonts for JP. Apache FOP supports them.

PDF rendering for base and JP Noto fonts:
![image](https://user-images.githubusercontent.com/5559926/166915215-f58c8f26-6b44-416e-bee4-a42269726df9.png)

I'll prepare two lists of fonts:
- base set (Regular+Bold) for 5 languages
- extended set (Regular + Bold) for 5 languages

to compare total size and choose them.

I think that we need to use base Sans/Serif/Mono Noto fonts + Region Specific Subsets.

**Comment by Intelligent2013** [comment]
From https://fonts.google.com/noto/specimen/Noto+Sans+JP:
Language support :  4 Languages

    Central Okinawan
    Central Okinawan, Japanese
    Japanese
    Japanese, Katakana 

From https://fonts.google.com/noto/specimen/Noto+Sans+KR:
Language support: 1 Language

    Korean 


I've tried to render PDF with text on Japanese in two fonts: 'Noto Serif JP' and 'Noto Serif KR'.

There are missing glyphs (`#`) in KR font for Japanese language:

![image](https://user-images.githubusercontent.com/5559926/167009461-47d8e838-bd38-4865-938a-6d28edc0d0e2.png)


In the log there are a few warning about missing glyphs:
```
WARNING: Glyph "?" (0x8b72) not available in font "NotoSerifKR-Regular".
ьр  05, 2022 10:02:44 PM org.apache.fop.events.LoggingEventListener processEvent
WARNING: Glyph "?" (0x8efd) not available in font "NotoSerifKR-Regular".
ьр  05, 2022 10:02:44 PM org.apache.fop.events.LoggingEventListener processEvent
WARNING: Glyph "?" (0x86ee) not available in font "NotoSerifKR-Regular".
ьр  05, 2022 10:02:44 PM org.apache.fop.events.LoggingEventListener processEvent
WARNING: Glyph "?" (0x5c02) not available in font "NotoSerifKR-Regular".
ьр  05, 2022 10:02:44 PM org.apache.fop.events.LoggingEventListener processEvent
WARNING: Glyph "?" (0x5727) not available in font "NotoSerifKR-Regular".
ьр  05, 2022 10:02:44 PM org.apache.fop.events.LoggingEventListener processEvent
WARNING: Glyph "?" (0x5bfe) not available in font "NotoSerifKR-Regular".
ьр  05, 2022 10:02:44 PM org.apache.fop.events.LoggingEventListener processEvent
WARNING: Glyph "?" (0x4fa1) not available in font "NotoSerifKR-Regular".
ьр  05, 2022 10:02:45 PM org.apache.fop.events.LoggingEventListener processEvent
```

So we need to specify all of them in the font-family.

**Comment by Intelligent2013** [comment]
Font weights:
- 'Black' (`font-weight="900"`) is using on BIPM cover page only.
- 'SemiBold' (`font-weight="600"`) is using on BIPM and Ribose (document number and version) on cover page only.
-'Medium' (`font-weight="500"`) is using on BIPM Appendix cover page, and BSI cover page only.
- 'DemiLight' isn't using at all.
- 'Light' (`font-weight="300"`) is using on BIPM coverpage, BSI, PAS cover page, title, ToC and back page, Ribose text.
- 'Thin' (`font-weight="100"`) is using on BIPM coverpage.

So I think that we can use 'base set' (Regular + Bold) of Noto CJK fonts  (https://github.com/metanorma/mn2pdf/issues/119#issuecomment-1118831891), total size ~300Mb.

**Comment by ronaldtse** [comment]
@Intelligent2013 agree with the base set of fonts, thanks!

**Comment by Intelligent2013** [comment]
The total file size of .zip files:
https://github.com/googlefonts/noto-cjk/releases/download/Sans2.004/05_NotoSansCJK-SubsetOTF.zip
https://github.com/googlefonts/noto-cjk/releases/download/Sans2.004/11_NotoSansMonoCJKjp.zip
https://github.com/googlefonts/noto-cjk/releases/download/Sans2.004/12_NotoSansMonoCJKkr.zip
https://github.com/googlefonts/noto-cjk/releases/download/Sans2.004/13_NotoSansMonoCJKsc.zip
https://github.com/googlefonts/noto-cjk/releases/download/Sans2.004/14_NotoSansMonoCJKtc.zip
https://github.com/googlefonts/noto-cjk/releases/download/Sans2.004/15_NotoSansMonoCJKhk.zip
https://github.com/googlefonts/noto-cjk/releases/download/Serif2.001/06_NotoSerifCJKSubsetOTF.zip
is ~545Mb.
We need only 30 .otf files from them. If we re-pack 30 used only .otf file into separate .zip in the fontist repository (similar to https://github.com/fontist/noto-fonts/releases/download/v1.0/noto-fonts-latn-1.0.zip), then we can decrease downloadable file size to 245Mb.

**Comment by Intelligent2013** [comment]
Noto fonts added in mn2pdf v1.45.

**Comment by ronaldtse** [comment]
@Intelligent2013 I have made the fonts available here now as release v1.1:
https://github.com/fontist/noto-fonts/releases/tag/v1.1

**Comment by Intelligent2013** [comment]
@ronaldtse thanks, I'll rebuild v1.45 with new url.

**Comment by Intelligent2013** [comment]
@ronaldtse thanks. Url added into mn2pdf release v1.46.
