### ISSUE TITLE
Auto-release mn2pdf package using a better method

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf#13]
https://korosuke613.hatenablog.com/entry/2019_12_18_github_registry_gradle

**Comment by CAMOBAP795** [comment]
@ronaldtse I can help with this if need because I done a similar task in the past

**Comment by ronaldtse** [comment]
@CAMOBAP795 actually we just got this working yesterday in the barcode4j repository 😉  

Since @Intelligent2013 just worked on this yesterday with barcode4j, perhaps he'd be in a better position to do this in mn2pdf?

**Comment by CAMOBAP795** [comment]
@ronaldtse agree

**Comment by Intelligent2013** [comment]
@ronaldtse ok, I'll make to publish mn2pdf as Github Maven Package similar to barcode4j.

**Comment by ronaldtse** [comment]
Thanks!

**Comment by Intelligent2013** [comment]
@ronaldtse 

Could you check that I have a rights to deploy packages into mn2pdf repository. I've setup a config similar to barcode4j and spent a lot of time to solve this issue:
`Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project mn2pdf: Failed to deploy artifacts: Could not transfer artifact com.metanorma.fop:mn2pdf:jar:1.7 from/to github (https://maven.pkg.github.com/metanorma/mn2pdf): Transfer failed for https://maven.pkg.github.com/metanorma/mn2pdf/com/metanorma/fop/mn2pdf/1.7/mn2pdf-1.7.jar 401 Unauthorized `
(https://github.com/metanorma/mn2pdf/runs/582628303)

FYI: in release.yml GITHUB_TOKEN is using for deploy mn2pdf-1.7,jar (unsuccessfully) into repository, but GH_TOKEN and GH_USERNAME are using for install barcode4j.jar from repository (successfully).

**Comment by ronaldtse** [comment]
We have PAT_TOKEN and PAT_USERNAME set in this repo, can you try them?

**Comment by Intelligent2013** [comment]
@ronaldtse thank you. It's working and .jar can be downloaded from:
https://maven.pkg.github.com/metanorma/mn2pdf/com/metanorma/fop/mn2pdf/1.7/mn2pdf-1.7.jar

For info:
- in release.yml we need to use two pairs of keys:
```
# for download barcode4j
GH_TOKEN: ${{ github.token }}
GH_USERNAME: ${{ github.actor }}
# for deploy mn2pdf
GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
GITHUB_USERNAME: ${{ secrets.PAT_USERNAME }}
```
- in settings.xml:
```
    <servers>
        <server>
            <id>metanorma</id>
            <username>${env.GH_USERNAME}</username>
            <password>${env.GH_TOKEN}</password>
        </server>
        <server>
            <id>metanorma_mn2pdf</id>
            <username>${env.GITHUB_USERNAME}</username>
            <password>${env.GITHUB_TOKEN}</password>
        </server>
    </servers>
```
- in pom.xml:
```
	<distributionManagement>
	 <repository>
		 <id>metanorma_mn2pdf</id>
		 <name>GitHub Metanorma Apache Maven Packages</name>
		 <url>https://maven.pkg.github.com/metanorma/mn2pdf</url>
	 </repository>
	</distributionManagement>
```
- note: `<id>metanorma_mn2pdf</id>` from pom.xml and from settings.xml should be equal.

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 ! It must have been difficult to get this combination working, really appreciate it!
