### ISSUE TITLE
mn2pdf.jar contains classes which should not be there

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/mn2pdf#15]
Packages which highly likely redundant:

 - `com.thoughtworks.qdox`- javadoc parser, I'm not sure that we use/need it
 - `org.junit.contrib.java.lang.system.internal`- test code
 - `org.w3c` - should be in JRE
 - `org.xml.sax` - should be in JRE

cc @Intelligent2013 @ronaldtse

**Comment by Intelligent2013** [comment]
@CAMOBAP795
- com.thoughtworks.qdox
 uses by FOP. I don't know about the behaviour of FOP if we remove it. How can we determine that this libraries are not critical to run?

- org.junit.contrib.java.lang.system.internal, org.w3c, org.xml.sax
agree,

**Comment by opoudjis** [comment]
Shrink this file. I can't check it into GitHub, there's a 100 MB limit.

**Comment by ronaldtse** [comment]
@opoudjis you're NOT supposed to check it into GitHub.

**Comment by opoudjis** [comment]
Compile it in the gem without checking it into GitHub? That's an exception, and does it need to be 114 MB anyway?

**Comment by ronaldtse** [comment]
Most of the 114MB are embedded fonts. Unless we move the embedded fonts out, that means we have to redistribute the fonts (which is fine)

**Comment by ronaldtse** [comment]
I've made a release for the Adobe Source fonts we use at https://github.com/metanorma/source-fonts . This can be easily extracted inside `~/.metanorma/fonts` by `mn2pdf`.

**Comment by ronaldtse** [comment]
Now taken care by @Intelligent2013 in https://github.com/metanorma/mn2pdf/pull/17 .

**Comment by Intelligent2013** [comment]
@CAMOBAP Is this issue relevant?

Size of mn2pdf is 20Mb now. `org.w3c` and `org.xml.sax` classes spent 250Kb only.
I found that these classes use in modules:
- jeuclid-core-3.1.14.jar:\org\w3c\dom\mathml
- batik-all-1.9.1.jar:\org\w3c\dom
(classes version 2017 year)
- xml-apis-1.3.04.jar:\org\xml\sax 
(classes version 2006 year)

I don't sure that if we'll remove them from jar, then all integrated modules will work ok for all features. 

Package org.junit.contrib.java.lang.system.internal will be removed from jar in next release.

**Comment by ronaldtse** [comment]
@Intelligent2013 agree, the size is small enough now, we can close this. Thanks @CAMOBAP for investigating.
