### ISSUE TITLE
Add `render/preprocess-xslt` pre-processing

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#169]
Source issue: https://github.com/metanorma/metanorma-ogc/issues/472

Presentation XML (OGC, for instance) may contain XSLT templates in `ogc-standard/render/preprocess-xslt`:

```xml
<ogc-standard xmlns="https://www.metanorma.org/ns/ogc" type="presentation" version="2.3.1">
...
	<render>
		<preprocess-xslt>
			<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns="http://www.w3.org/1999/xhtml" version="1.0">
				<xsl:output method="xml" version="1.0" encoding="UTF-8" indent="no"/>
				<xsl:strip-space elements="*"/>
				<!-- note/name -->
				<xsl:template match="*[local-name() = 'note']/*[local-name() = 'name']">
					<xsl:copy>
						<xsl:apply-templates select="@*|node()"/>
						<xsl:if test="normalize-space() != ''">:<tab/>
						</xsl:if>
					</xsl:copy>
				</xsl:template>
			</xsl:stylesheet>
		</preprocess-xslt>
	</render>
...
```
These templates should be added at the end of main XSLT.
Before:
-  convert 'note/label' to `*[local-name() = 'note']/*[local-name() = 'label']` via mn2pdf in Java
-  set `priority="5"` to override another existing identical templates in the XSLT.

**Comment by Intelligent2013** [comment]
> convert 'note/label' to `*[local-name() = 'note']/*[local-name() = 'label']` via mn2pdf in Java

currently it done via xslt on-fly for `template match="..."` only. It's very complex task to replace xpath by 'namespace free' xpath for all XSLT entities like functions (`concat`, `translate`), `test`, `select`, etc. Further if need, 'namespace free' XPath task can be solved by converting source XML to XML without namespace by templates similar to `mode="remove_namespace"` in https://github.com/metanorma/mnconvert/blob/main/src/main/resources/mn2xml.xsl.

**Comment by Intelligent2013** [comment]
Done.

**Comment by Intelligent2013** [comment]
Note: done for `ogc-standard` documents only.

java\org\metanorma\fop\SourceXMLDocument.java:
```
XPathExpression query = xPath.compile("//*[contains(local-name(),'ogc-standard')]/*[local-name()='render']/*[local-name()='preprocess-xslt']/*[local-name()='stylesheet']");
```

`ogc-standard` should be replaced by `-standard` for another SDOs.

**Comment by ronaldtse** [comment]
@Intelligent2013 is there a reason this is OGC specific? Or can it be applied to all flavors?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 is there a reason this is OGC specific? Or can it be applied to all flavors?

@ronaldtse it can be applied to all flavors by replacing `ogc-standard` to `-standard` as described above. I've made OGC specific specially for preventing side effect due the comment https://github.com/metanorma/metanorma-ogc/issues/472#issuecomment-1364872391. I don't know how (globally or OGC only) currently `preprocess-xslt` feature realized. May be `preprocess-xslt` appears in all XMLs, but correct one is for OGC only...
