### ISSUE TITLE
System.getProperty("user.home") fails to return home folder defined by snap

### ISSUE THREAD

**Issue by maxirmx** [metanorma/mn2pdf#183]
In the environment under discussion  fontist  looks for user home with ```Dir.home```
Then a folder with a name likе  ```/home/maxirmx/snap/metanorma/137/.fontist/fonts ``` is created and fontist succesfully load fonts there  [this is snap user specific directory explained by @ronaldtse above]

mn2pdf uses ```System.getProperty("user.home")``` , nothing is created, an attempt by metanorma to load a file to ```/home/maxirmx/.metanorma/font ``` fails  (no such file or directory)
If I create the folder ```/home/maxirmx/.metanorma/font``` an attempt to load a file by metanorma still fails (Permission denied), 

Since _"snap blocks all the access to the hidden files/dirs in the HOME directory even it connected to the home interface"_   there is no way to use .metanorma in the real home folder

_Originally posted by @maxirmx in https://github.com/metanorma/packed-mn/issues/200#issuecomment-1461690679_

**Comment by CAMOBAP** [comment]
Related https://github.com/metanorma/metanorma-snap/issues/14

**Comment by CAMOBAP** [comment]
@maxirmx @Intelligent2013 @ronaldtse 

I am sure that issue has nothing to do with mn2pdf.jar by itself. 

Event if by some have we will able to calculate how actual `$HOME` snap will not let you write to this directory.

The right solution should be to run `snap connect metanorma:home :home` after `snap install metanorma`

I can't ready to use Linux VM right now, @maxirmx may I ask you to check if `snap connect metanorma:home :home` works?

**Comment by maxirmx** [comment]
Ok, I will look at it

**Comment by maxirmx** [comment]
@CAMOBAP ```snap connect metanorma:home :home``` does not have. 
Still got
```
Can't downloaded a file:  /home/maxirmx/metanorma/fonts/noto-fonts-latn.1.1.zip (Permission deinied)
```
I guess it happens because access to hidden files is blocked by home interface
https://forum.snapcraft.io/t/the-home-interface/7838
and `personal files` interafce is required
https://forum.snapcraft.io/t/the-personal-files-interface/9357

**Comment by ronaldtse** [comment]
@CAMOBAP @maxirmx mentioned in the OP, a Snap package "should not" use the home directory. We should only use the Snap user directory. We should not even require the user to provide our snap package with home directory access. This is probably why our package was sent to manual review.

Instead, we need to change Gem behavior to use a "metanorma home/cache directory" depending on package configuration:
* If inside a docker container, use `~/.metanorma`
* If inside a Snap package, use `$SNAP_USER_DATA/metanorma`

There is really no way for us to escape this Snap restriction.

I think this really means that we should create Snap packages for all our dependencies that we control:
* Fontist
* Relaton
* Metanorma

Otherwise it would be very difficult to control how the dependencies work inside a single Snap package.

**Comment by Intelligent2013** [comment]
> I am wondering why mn2pdf does this if metanorma provides font_mainfest file with paths to required fonts? Or there is some other use case?

@CAMOBAP mn2pdf installs the additional fonts for cases when there are missing glyphs in the fonts installed by fontist.

**Comment by maxirmx** [comment]
I think we can try : 
- Call mn2pdf.jar with -Duser.home=<user.home defined in Ruby>
- Replace getProperty with getenv in Java code

@CAMOBAP @Intelligent2013  Would you like me to do it ?

**Comment by Intelligent2013** [comment]
@maxirmx I think the approach with redefined property

> Call mn2pdf.jar with -Duser.home=<user.home defined in Ruby>

is best than using of the environment variable, because we don't know which environment variable is using for user's home directory on each platform.

I've tested with JVM parameter `-Duser.home="test"` and it redefines this property.

**Comment by ronaldtse** [comment]
Re: mn2pdf installs additional fonts — it should not, but if it is really necessary it should use the same directory. If this is about the default mn2pdf Noto fonts, I wonder if we should separate the Ruby fontist directories vs the mn2pdf font directories. (The other alternative is to port Fontist formula installs to Java, which would also be a good thing).

**Comment by ronaldtse** [comment]
> is best than using of the environment variable, because we don't know which environment variable is using for user's home directory on each platform.

Agree.

**Comment by CAMOBAP** [comment]
@Intelligent2013 are there cases when mn2pdf.jar can be used independently of `metarnoma`?

I can propose to pass `user.home` property from [`mn2pdf-ruby`](https://github.com/metanorma/mn2pdf-ruby/blob/main/lib/mn2pdf.rb), something like:

```
@@ -15,6 +15,8 @@ module Mn2pdf
       options << "-Dapple.awt.UIElement=true"
     end

+    options << "-Duser.home=#{Dir.home}"
+
     options
   end

```

**Comment by ronaldtse** [comment]
> are there cases when mn2pdf.jar can be used independently of metarnoma?

I think only @Intelligent2013 uses that independently for testing.

**Comment by Intelligent2013** [comment]
> are there cases when mn2pdf.jar can be used independently of `metarnoma`?

@CAMOBAP only for debugging and testing purposes (me). End-users don't run mn2pdf directly.

**Comment by CAMOBAP** [comment]
mn2pdf-ruby@1.65.1 will pass `-Dhome.user` to JVM

**Comment by ronaldtse** [comment]
@CAMOBAP then is this task now fixed?

**Comment by CAMOBAP** [comment]
I suppose yes
