### ISSUE TITLE
Update XPath for `preprocess-xslt`

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#190]
Source issue: https://github.com/metanorma/metanorma-ogc/issues/522#issuecomment-1489663199

As titled.

**Comment by opoudjis** [comment]
It's going to be:

`xPath.compile("//*[contains(local-name(),'ogc-standard')]/*[local-name()='metanorma-extension']/*[local-name()='render']/*[local-name()='preprocess-xslt'][not(@format) or contains(@format, 'pdf')]/*[local-name()='stylesheet']");`

**Comment by Intelligent2013** [comment]
https://github.com/metanorma/metanorma-ogc/issues/522#issuecomment-1492974257:
Closing.
