### ISSUE TITLE
PDF issues: Metanorma uses PDF features from 1.4+ but it is tagged as `%PDF-1.4`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf#202]
The PDF Header line is `%PDF-1.4` - Metanorma is already using PDF features from later versions but if you bump this to PDF 1.7 then it will be "clean" and correct. Note that I am NOT recommending you use "%PDF-2.0". Yet.

From https://github.com/metanorma/mn2pdf/issues/201

**Comment by Intelligent2013** [comment]
From the `Arlington PDF Model`s `TestGrammar` log:
```
[1;36mInfo: Header is version PDF 1.4[0m
[1;36mInfo: Document Catalog/Version is PDF 1.5[0m
```

**Comment by Intelligent2013** [comment]
Apache FOP config updated.
```
[1;36mInfo: Header is version PDF 1.7[0m
```

**Comment by Intelligent2013** [comment]
Version change causes the error https://github.com/metanorma/mn2pdf/issues/205

> `Cannot change the version of this PDF document`
