### ISSUE TITLE
PDF issues: do not generate ProcSet array resources

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf#203]
Metanorma generates ProcSet array resources. These were deprecated back in PDF 1.4 in the very early 2000s - please don't generate as they are a complete waste of bytes!

From https://github.com/metanorma/mn2pdf/issues/201

**Comment by Intelligent2013** [comment]
Currently, the PDF (for instance, `rice-en.final.presentation.pdf`) contains only these data:
`/ProcSet [/PDF /ImageB /ImageC /Text]`

From `fop-2.8\fop-core\src\main\java\org\apache\fop\pdf\PDFResources.java`:
```java
        PDFArray procset = new PDFArray(this);
        procset.add(new PDFName("PDF"));
        procset.add(new PDFName("ImageB"));
        procset.add(new PDFName("ImageC"));
        procset.add(new PDFName("Text"));
        put("ProcSet", procset);
```
