### ISSUE TITLE
Debug mode in the document attribute

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#211]
Currently `mn2pdf` supports the debug mode (generates intermediate XSL-FO, IF, config files) via CLI parameter `--debug`, `-d`.
But there isn't possibility to pass this parameter via metanorma command line:
```
bundle exec metanorma -t iso -x pdf rice-en.final.adoc 
```

To do:  support debug mode via adoc document attribute:
```
:presentation-metadata-pdfdebug: true
```
If Metanorma XML contains:
```xml
<presentation-metadata><pdfdebug>true</pdfdebug></presentation-metadata>
```
then it's equal `--debug`.

**Comment by ronaldtse** [comment]
@Intelligent2013 isn't this supposed to be a Metanorma CLI option instead of a document attribute? The PDF debug function is clearly a runtime issue not a document issue. I'm not sure if we want to pollute the document with debug options.

**Comment by Intelligent2013** [comment]
@ronaldtse you're right. Just I would like to minimize the change requests for Metanorma CLI. Ok, I'll add the ticket into the `metanorma-cli` repository.

**Comment by Intelligent2013** [comment]
Added: https://github.com/metanorma/metanorma-cli/issues/308

**Comment by ronaldtse** [comment]
> @ronaldtse you're right. Just I would like to minimize the change requests for Metanorma CLI. Ok, I'll add the ticket into the `metanorma-cli` repository.

Thank you, I totally understand but I want us to do things the right way, not the convenient way for internal administration reasons.
