### ISSUE TITLE
Math block: Insert default white space between number and parentheses

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn2pdf#218]
Currently, there is no default space between a number and an opening parentheses, in math environment.

Taking this code as example:

```adoc
[cols="a,a",options="unnumbered"]
|===
|
stem:[1 (f_a = f_b = f_c = 0)]
|
stem:[7 (f_i = 2)]
|
stem:[2 (f_d = 1)]
|
stem:[8 (f_j = 2)]
|
stem:[3 (f_e = 1)]
|
stem:[9 (f_k = 2)]
|
stem:[4 (f_f = 1)]
|
stem:[10 (f_l = 1)]
|
stem:[5 (f_g = 1)]
|
stem:[11 (f_m = 1)]
|
stem:[6 (f_h = 1)]
|
|===
````

Renders:
![issue7-generated-pdf](https://github.com/metanorma/mn2pdf/assets/33627611/6e73f099-585e-43ec-a182-2c6949863130)

To show a comparison, this is the output in HTML:
![issue7-generated-html](https://github.com/metanorma/mn2pdf/assets/33627611/a46c769c-1b04-435f-9678-f61481454c4f)

**Comment by Intelligent2013** [comment]
It's jEuclid issue:
![image](https://github.com/metanorma/mn2pdf/assets/5559926/54c0dbb4-2e4d-4aa8-bb9f-138bcebb9557)

I'll find a workaround solution.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://github.com/metanorma/mn2pdf/assets/5559926/6b6d8c08-acf1-407a-8976-62f751be4df5)
