### ISSUE TITLE
Math: Vertical double bars render too separate

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn2pdf#221]
*In relation to https://github.com/metanorma/pdfa-iso-32000-2/issues/5*

```adoc
||"TP" - "cp"||
````

renders in PDF:
![issue9-generated-pdf](https://github.com/metanorma/mn2pdf/assets/33627611/1ac6a5fc-d0d3-41a9-b0c1-9be9291b5a9c)

In HTML output:
![issue9-generated-html](https://github.com/metanorma/mn2pdf/assets/33627611/13acbcb1-14ae-4cfd-abc1-609ebd7d18e6)

**Comment by Intelligent2013** [comment]
This is a side-effect from https://github.com/metanorma/metanorma-standoc/issues/778.
I have to check the preceding/following math elements additionally.

**Comment by Intelligent2013** [comment]
Issue fixed:
![image](https://github.com/metanorma/mn2pdf/assets/5559926/fa51a78a-8a4a-4c73-a16a-a9526ab30950)
