### ISSUE TITLE
Support inline images in PDF

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn2pdf#225]
It seems that inline images (`image:...[]`) are not supported in PDF output:

```adoc
____
Text introduced or altered by Amendment(s) No. 1 (and No. 2, respectively)
is indicated in the text by tags image:A1.png[] (and image:A2.png[]).
Minor editorial changes are not tagged.
____
````

PDF:
![issue1-pdf](https://github.com/metanorma/mn2pdf/assets/33627611/bfef7968-2b22-4b9f-b1b1-ac0724c8c32d)

HTML:
![issue1-html](https://github.com/metanorma/mn2pdf/assets/33627611/1cecf5d6-19b4-4343-a2fb-c7bf147dd04f)

Source: https://github.com/metanorma/mn-samples-bsi/pull/304

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://github.com/metanorma/mn2pdf/assets/5559926/76e524e1-954c-4ce4-8c58-a2798d4a469c)
