### ISSUE TITLE
Add image cache folder feature

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#229]
Source ticket: https://github.com/metanorma/metanorma-ogc/issues/600

To do: in case of big XML (>50mb) extract images from the XML to the temporarily folder, so the XML will contains the file links only.

**Comment by ronaldtse** [comment]
Is this an mn2pdf thing or a general Metanorma XML feature?

**Comment by Intelligent2013** [comment]
> Is this an mn2pdf thing or a general Metanorma XML feature?

@ronaldtse mn2pdf thing.

But I've found the Metanorma document attribute `:data-uri-image: false` (https://www.metanorma.org/author/ref/document-attributes/#visual-appearance) that allows to don't integrate the images inline in the XML. I this case the Presentation XML contains the images paths instead of base64 encoded images, like this:
```
<image src="images/figure-overview.png" ...
```

`:data-uri-image: false` should solve the initial issue `[mn2pdf] Exception in thread "main" java.lang.OutOfMemoryError: Java heap space`.

`:data-uri-image:` affects on HTML output also:
> Encode all images in HTML output as inline data-URIs.

@ronaldtse now I don't sure that I have to do it:

> To do: in case of big XML (>50mb) extract images from the XML to the temporarily folder, so the XML will contains the file links only.

What do you think?  `:data-uri-image: false` is enough to solve the issue, or should I 'extract images from XML into the temp folder` in any case?

**Comment by Intelligent2013** [comment]
`mn2pdf` updated. Now `mn2pdf` extracts the images from base64 to the temporarily folder on disk. I.e. base64 streams don't spent the memory in XSLT processing.
