### ISSUE TITLE
PDF/A-3A validation: If present, the F key's Print flag bit shall be set to 1 and its Hidden, Invisible, ToggleNoView, and NoView flag bits shall be set to 0

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#275]
Source issues: https://github.com/metanorma/mn2pdf/issues/264

veraPDF report:

- `root/document[0]/pages[3](11 0 obj PDPage)/annots[0](113 0 obj PDMarkupAnnot)`
```xml
<rule specification="ISO 19005-3:2012" clause="6.3.2" testNumber="2" status="failed" failedChecks="2">
  <description>If present, the F key's Print flag bit shall be set to 1 and its Hidden, Invisible, ToggleNoView, and NoView flag bits shall be set to 0</description>
  <object>PDAnnot</object>
  <test>F == null || ((F &amp; 1) == 0 &amp;&amp; (F &amp; 2) == 0 &amp;&amp; (F &amp; 4) == 4 &amp;&amp; (F &amp; 32) == 0 &amp;&amp; (F &amp; 256) == 0)</test>
  <check status="failed">
    <context>root/document[0]/pages[3](11 0 obj PDPage)/annots[0](113 0 obj PDMarkupAnnot)</context>
  </check>
</rule>
```

Note: occurs in `iec-rice-en.presentation.pdf` and `iec-rice-fr.presentation.pdf` only.

**Comment by petervwyatt** [comment]
This just means that `/F 4` needs to be explicit in each annotation dictionary (except Popup annotations). See Table167 in ISO 32000-2:2020 (no-cost version).

**Comment by Intelligent2013** [comment]
Currently, XFDF has the flags `nozoom,norotate`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xfdf xmlns="http://ns.adobe.com/xfdf/">
	<annots>
		<text color="#FFC333" opacity="0.600000" flags="nozoom,norotate" date="2017-01-01T00:00:00Z" page="3" rect="70.866,593.864" title="ISO">...
```
which means bitmask `11000` regarding `Table 167` in ISO 32000-2:2000.
Decimal value is 24:
![image](https://github.com/user-attachments/assets/aa50bda4-b286-4071-a33e-d1922b4a6b7d)

To do: add `print` flag.

**Comment by Intelligent2013** [comment]
Fixed in https://github.com/metanorma/mn2pdf/pull/282/

**Comment by Intelligent2013** [comment]
Fixed in https://github.com/metanorma/mn2pdf/releases/tag/v2.00.
