### ISSUE TITLE
Also release Ruby gem containing mn2pdf on release

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf#28]
https://github.com/metanorma/metanorma/issues/115

> Let's create a separate mn2pdf gem, that includes an identically versioned mn2pdf.jar that metanorma can depend on in its gemspec file.

Either in this repo or separate repo. What do you think @CAMOBAP795 ?

**Comment by CAMOBAP795** [comment]
I think better to create separate it in separate repo, my proposal s:
 - rename mn2pdf to mn2pdf-jar
 - use mn2pdf for Ruby gem

@ronaldtse @Intelligent2013 how do you think?

**Comment by ronaldtse** [comment]
@CAMOBAP795 just released at https://github.com/metanorma/mn2pdf-ruby :wink:

We won't change name of current repo.
