### ISSUE TITLE
Provide command line option to show version number

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf#29]
We need mn2pdf.JAR to show its version number so we can confirm the version in the Ruby gem.

**Comment by Intelligent2013** [comment]
@ronaldtse I've added parameter '-v' (or --version) to show version of mn2pdf.jar The latest release here:
https://github.com/metanorma/mn2pdf/releases/download/v1.12/mn2pdf-1.12.jar

**Comment by Intelligent2013** [comment]
@ronaldtse Version 1.12 is broken. Use 1.13: https://github.com/metanorma/mn2pdf/releases/download/v1.13/mn2pdf-1.13.jar

**Comment by ronaldtse** [comment]
Done, thanks @Intelligent2013 !
