### ISSUE TITLE
Quote paths

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mn2pdf#42]
One of the metanorma gem tests for the puppeteer PDFs, which fails for XSL FO PDFs, is to generate PDFs in a directory that contains spaces.

Mn2pdf.convert(url_path, output_path, xsl_stylesheet) should succeed if any of its arguments contains a directory with spaces: the paths should be quoted, and a Java command like

`java -Xss5m -Xmx1024m -jar /Users/nickn/.rvm/gems/ruby-2.6.6/gems/mn2pdf-1.18/lib/../bin/mn2pdf.jar --xml-file spec/assets/test/dir with path/a.xml --xsl-file spec/assets/test/iso.international-standard.xsl --pdf-file spec/assets/test/dir with path/a.pdf`

should not be issued.

Once this is fixed, I can reenable the test in metanorma.

**Comment by Intelligent2013** [comment]
@opoudjis 
space is a argument separator in command line (https://docs.oracle.com/javase/9/tools/java.htm#JSWOR624):

> java [options] -jar jarfile [args...]
> ...
> args
>    Specifies the arguments passed to the main method separated by spaces

 This issue can be fixed in metanorma gem by enclosing each parameter in qoutes like this:

```
java -Xss5m -Xmx1024m -jar "/Users/nickn/.rvm/gems/ruby-2.6.6/gems/mn2pdf-1.18/lib/../bin/mn2pdf.jar" --xml-file "spec/assets/test/dir with path/a.xml" --xsl-file "spec/assets/test/iso.international-standard.xsl" --pdf-file "spec/assets/test/dir with path/a.pdf"
```
