### ISSUE TITLE
Add split PDF feature

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#45]
For https://github.com/metanorma/metanorma-bipm/issues/4

**Comment by ronaldtse** [comment]
@Intelligent2013 the covers of the single language also need to be single language. How should we achieve this?

**Comment by Intelligent2013** [comment]
@ronaldtse 
I propose to add a command-line parameter `split-by-language'. In this case these mn2pdf will produce 5 PDFs:
1. produce `Bilingual version, with bilingual cover`, usual case
2. produce  `French cover` (by using xslt again with parameter cover='fr', that will produce cover page only)
3. produce  `English cover` (by using again with parameter cover='en', that will produce cover page only)
4. split PDF from 1. by using for example Apache PDFBox API into two PDFs, without first(cover) page
  4.1. concatenate each French part with page from 2.
  4.2. concatenate each English part with page from 3.
5. delete PDF files from 2. and 3.

Really the compicated task is split a title into 4 parts, to displays each part with own font (Light ... Regular ... Bold).

**Comment by Intelligent2013** [comment]
One another more simpler solution. Produce 3 PDFs.
When parameter `split-by-language` set and there is param `additionalXMLs` in command line, then
1, produce `Bilingual version, with bilingual cover`, usual case (with using parameter `additionalXMLs` as from IEC xslt)
2. produce `French version with French cover`, process PDF only for first XML and get the total page numbers (it should returned by FOP)
3. produce `English version with English cover`, process PDF only for second XML (from additionalXMLs) with param `initialPage` (passed from 2.)

**Comment by Intelligent2013** [comment]
Done. This feature will be in release 1.22.

To produce 3 PDF for BIPM flavor:
```
java -Xss5m -Xmx1024m mn2pdf-v1.22.jar  --xml-file collection.presentation.xml  --xsl-file bipm.brochure.presentation.xsl  --pdf-file bipm.pdf --split-by-language
```

3 PDFs will be created:
- **bipm.pdf**
![изображение](https://user-images.githubusercontent.com/5559926/94299786-ced97800-ff70-11ea-9bbc-bf7763a91bd3.png)
(please ignore font-weight, it will be fixed)

with English abstract on physical page 115 (logical 113)
![изображение](https://user-images.githubusercontent.com/5559926/94300141-398ab380-ff71-11ea-99e6-44b227af044a.png)


- **bipm_fr.pdf**
![изображение](https://user-images.githubusercontent.com/5559926/94299851-e4e73880-ff70-11ea-959c-9877dfaacbc4.png)

- **bipm_en.pdf**
![изображение](https://user-images.githubusercontent.com/5559926/94299953-01837080-ff71-11ea-9af9-409bb6a90ae4.png)

with English abstract on physical page 7 (logical 113)
![изображение](https://user-images.githubusercontent.com/5559926/94300066-2546b680-ff71-11ea-8f42-37a4e74319be.png)

**Comment by opoudjis** [comment]
In order to append `--split-by-language` to call to mn2pdf, need to update ruby wrapper to take an additional argument for trailing options.
