### ISSUE TITLE
Customizing the "Encoder Software" field of the generated PDF

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf#48]
<img width="261" alt="Screen Shot 2020-09-20 at 9 43 17 AM" src="https://user-images.githubusercontent.com/11865/93692423-b78c2c00-fb25-11ea-9296-4d3845dbab68.png">

Can we customize this message for Encoder Software? We should use "Ribose Metanorma mn2pdf version x.x." if possible.

**Comment by Intelligent2013** [comment]
Fixed.
![изображение](https://user-images.githubusercontent.com/5559926/93750902-e927f480-fc04-11ea-9d42-d1753213327a.png)

**Comment by Intelligent2013** [comment]
Done in version 1.21.
