### ISSUE TITLE
There aren't math svg for BIPM

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#51]
Source issue: https://github.com/metanorma/bipm-si-brochure/issues/47

In the resulted PDF there aren't math equations:

![изображение](https://user-images.githubusercontent.com/5559926/99260957-1d96e600-282d-11eb-9f3a-91da8df0ee54.png)

(see `values of ... and ... . `)

BIPM xslt uses Open Type Font `STIX2Math.otf`.

Java doesn't support OTF in versions below Java 8, Update 241 (https://www.oracle.com/java/technologies/javase/8u241-relnotes.html).

```
 client-libs/2d
➜ Support for OpenType CFF Fonts

Previously, Oracle JDK 8 did not include OpenType CFF fonts (.otf fonts) into the standard logical fonts (such as "Dialog" and "SansSerif"). This resulted in missing glyphs when rendering text. In the most extreme cases where only CFF fonts were installed on the system, a Java exception could be thrown.

Several Linux distributions were affected by this issue because they rely on CFF fonts to support some languages, which is common for CJK (Chinese, Japanese, and Korean) languages.

Oracle JDK 8 now uses these CFF fonts, and this issue has been resolved.

See http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8209672
``` 

**The solution**: Java 8u241 and above should be used.

**Comment by ronaldtse** [comment]
@Intelligent2013 could we detect for the minimum Java 8 version due to this problem? Could you also document this requirement in the README? Thanks.

**Comment by Intelligent2013** [comment]
@ronaldtse mininum Java version is 1.8.0_241 (Java8, Update 241).
 README updated.
