### ISSUE TITLE
Situation with index term cross-reference

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#54]
Currently, when there are several instances of an index term in one page, the last one is the one that gets cross-referenced in the index. Making previous instances hidden to the user when cross-reference is clicked (i.e. only the last iteration is shown).

For better explanation, consider this example:

![capture1](https://user-images.githubusercontent.com/33627611/104868601-39e0fd00-591a-11eb-9298-30bed73a12e4.PNG)

As shown above, there are several instances of "absolute units" highlighted in yellow, which corresponds to one term in the index:
![Capture3](https://user-images.githubusercontent.com/33627611/104867973-7ad81200-5918-11eb-8c46-07332a5cec84.PNG)

So, all the instances are referenced to the page 95. Now, when we click on the page number, we get:

![Capture3](https://user-images.githubusercontent.com/33627611/104869056-61849500-591b-11eb-8bb5-73d926f4d568.PNG)

The cross-reference lead us to the last instance, showing only this one and covering up the other ones.

Is it possible to use the first instance instead in order to get a broader view of the instances?

**Comment by manuel489** [comment]
Source XML: [si-brochure-en.presentation.zip](https://github.com/metanorma/mn2pdf/files/5827670/si-brochure-en.presentation.zip)

**Comment by Intelligent2013** [comment]
Issue fixed.
Latest PDF: [si-brochure-en.presentation.pdf](https://github.com/metanorma/mn2pdf/files/5831172/si-brochure-en.presentation.pdf)
