### ISSUE TITLE
Number sign in math environment

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#56]
In table of contents of SI Brochure, number sign ('#') is shown in math environment (instead of white space):

![issue1-generated](https://user-images.githubusercontent.com/33627611/105779127-12a2b500-5f44-11eb-8b6a-6b15a1e8d9b4.PNG)

This capture is from `mep-wgfs-nm267-27Al_1121THz.adoc` file.

**Comment by Intelligent2013** [comment]
@manuel489 could you attach a source xml please? In my environment the resulted PDF without ToC at all.

**Comment by manuel489** [comment]
@Intelligent2013 , sure. This output comes from the compiled files that @opoudjis provided us:

[27Al_xml.zip](https://github.com/metanorma/mn2pdf/files/5873714/27Al_xml.zip)

**Comment by manuel489** [comment]
> @manuel489 could you attach a source xml please? In my environment the resulted PDF without ToC at all.

Yes, same here. If generated the document myself, I also get a PDF without ToC.

**Comment by Intelligent2013** [comment]
Fixed. Now math in toc titles renders as mathml, not text.
![изображение](https://user-images.githubusercontent.com/5559926/105867379-1565de80-6006-11eb-807c-b2d912decee9.png)
