### ISSUE TITLE
Hyphen rendered as em-dash

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#57]
Currently, when we type a isolated hyphen (`-`), an em-dash seems to be rendered. 

For example, `188 - 200` renders as

![Capture1](https://user-images.githubusercontent.com/33627611/105782324-b0997e00-5f4a-11eb-85ca-a3b035567840.PNG)

Is there a reason for this setting? (Knowing that I could use `--` to render an em-dash.)
I think an n-dash is more suitable.

**Comment by Intelligent2013** [comment]
Source mep-wgfs-nm237-115In_1267THz.adoc:
```
* [[[riehle,6]]], F. Riehle, P. Gill, F. Arias, L. Robertsson: The CIPM List of Recommended Frequency Standard Values: Guidelines and Procedures; _Metrologia_ *55*, 188 - 200 (2018)
```
`188 - 200` - hex code `2D`.

Source mep-wgfs-nm237-115In_1267THz.presentation.xml:
```xml
<bibitem id="riehle">
<formattedref format="application/x-isodoc+xml">F. Riehle, P. Gill, F. Arias, L. Robertsson: The CIPM List of Recommended Frequency Standard Values: Guidelines and Procedures; <em>Metrologia</em> <strong>55</strong>, 188 — 200 (2018)</formattedref>
<docidentifier type="metanorma">[6]</docidentifier>
</bibitem>
```
`188 — 200` - hex code 2014 (Em Dash).

So no issues in xslt/pdf, it renders as in xml.

**Comment by manuel489** [comment]
Wow, ok. Thanks @Intelligent2013, I'll ping Nick. Closing.
