### ISSUE TITLE
Long slash symbol in math environment

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#58]
I think that the slash symbol (/) coming from the `//` markup is a little bit large:

````
stem:[u_c//y = 1 xx 10^(−10)]
````

Generated: 
![issue2-generated](https://user-images.githubusercontent.com/33627611/105791240-15a99f80-5f5c-11eb-88ec-4d763b7476e9.PNG)

Original:
![issue2-original](https://user-images.githubusercontent.com/33627611/105791271-23f7bb80-5f5c-11eb-8caf-a7a606abcf18.PNG)

**Comment by Intelligent2013** [comment]
Looks like it's one another jEuclid bug.

Let's simple xml:
```
<math xmlns="http://www.w3.org/1998/Math/MathML">
	<mi>a</mi>
	<mo>/</mo>
	<mi>b</mi>
</math>
```
![изображение](https://user-images.githubusercontent.com/5559926/105865290-d46cca80-6003-11eb-9db0-f4f4d65ce487.png)

If we add a hairspace (200A) after `/`:
![изображение](https://user-images.githubusercontent.com/5559926/105865410-f6fee380-6003-11eb-947a-bf97a765d210.png)
we get smaller height, but small space added after /.

If we replace `mo` to `mn`:
![изображение](https://user-images.githubusercontent.com/5559926/105866190-ca979700-6004-11eb-8fb4-b153f9ccb06e.png)

So source math will renders as:
![изображение](https://user-images.githubusercontent.com/5559926/105866318-ebf88300-6004-11eb-9538-becc5d53b811.png)

I need to check `mo` -> `mn` replacement (xslt on-fly) on whole brochure.

**Comment by Intelligent2013** [comment]
One more solution - add attribute `stretchy='false'` (https://sourceforge.net/p/jeuclid/bugs/37/):
`<mo stretchy='false'>/</mo>`

![изображение](https://user-images.githubusercontent.com/5559926/105878205-d473c700-6011-11eb-8654-a21c8bd57b2e.png)

XSLT updated.
