### ISSUE TITLE
width table attribute has no effect in PDF output

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#59]
I don't know if this behavior is wanted, so I report.
The `width` attribute (in tables) seems to have no effect in PDF outputs. It remains at 100% in any case:

*Example:*
````
.GML geometric property types mapped to SQL/MM types.
[cols="2",options="header",width="70%"]
|===
|GML Geometric Property Type |Equivalent SQL/MM Type

|gml:PointPropertyType |ST_Point
|gml:CurvePropertyType |ST_LineString.
|gml:SurfacePropertyType |ST_Polygon
|gml:GeometryPropertyType |ST_Geometry
|gml:MultiPointPropertyType |ST_MultiPoint
|gml:MultiCurvePropertyType |ST_MultiCurve
|gml:MultiSurfacePropertyType |ST_MultiSurface
|gml:MultiGeometryPropertyType |ST_GeomCollection
|===
````

*DOC output:*
![width-doc](https://user-images.githubusercontent.com/33627611/106390179-8538e800-63bd-11eb-8498-927f1ebb1f7b.PNG)

*PDF output:*
![width-pdf](https://user-images.githubusercontent.com/33627611/106390183-879b4200-63bd-11eb-90b3-774461009c3a.PNG)

@ronaldtse, could you confirm if this behavior is wanted?

**Comment by ronaldtse** [comment]
I don't think we want to specify "whole table width". @manuel489 is this really necessary?

**Comment by manuel489** [comment]
Hmm, well, maybe it's not that important.
But sometimes I like to define it to enhance esthetics.
Ok @ronaldtse, thanks! Closing.

**Comment by ronaldtse** [comment]
@manuel489 the esthetics part should be handled by column width percentage 😉 

Unless does @Intelligent2013 have a better suggestion with not using full width tables?

**Comment by Intelligent2013** [comment]
@ronaldtse  I've added the attribute `@width` for table, and for columns processing a month ago already (https://github.com/metanorma/mn-native-pdf/issues/299) for https://github.com/metanorma/metanorma-standoc/issues/250.

@manuel489 Could you attach the XML here, please? I can't generate XMLs in my environment (Win and Ubuntu).

**Comment by manuel489** [comment]
@Intelligent2013, sure. The XML is contained in this folder: [10-100r3.zip](https://github.com/metanorma/mn2pdf/files/5905689/10-100r3.zip)

**Comment by Intelligent2013** [comment]
Here is my resulted PDF:
![изображение](https://user-images.githubusercontent.com/5559926/106498739-be15b180-64d0-11eb-9c6b-abdbf0119c7c.png)

Table has width 70%. But I think it should be centered.

[document.presentation.pdf](https://github.com/metanorma/mn2pdf/files/5905739/document.presentation.pdf)

**Comment by manuel489** [comment]
All good here, thanks!
