### ISSUE TITLE
Right space in comma separate items -- math environment

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#61]
This is about an enhancement that I recommend to address.
Currently, the comma separate elements in math environments are showing too tight to each other.

**For example:**

````
("Vertex"_1, "Vertex"_2)
````

renders as
![issue2-pdf](https://user-images.githubusercontent.com/33627611/106396275-4dda3380-63dd-11eb-9a7b-d6ee8bbb61e1.PNG)

If we look at normal AsciiDoc output:
![issue2-asciidoc](https://user-images.githubusercontent.com/33627611/106396247-2e430b00-63dd-11eb-918b-9cc01ad247f1.PNG)

There is a small white space at the right of the comma by default.

**Looking at another example:**

````
(vartheta_2, varphi_2)
````

renders:
![issue2-pdf2](https://user-images.githubusercontent.com/33627611/106396349-bd502300-63dd-11eb-9375-3347cb8106f8.PNG)

Is it possible to add a tiny space (by default) at the right of the comma to enhance esthetics?

**Comment by ronaldtse** [comment]
Agree. Could this be done @Intelligent2013 ? Thanks!

**Comment by Intelligent2013** [comment]
Done. 
![изображение](https://user-images.githubusercontent.com/5559926/106449041-9b65a780-6494-11eb-8e31-fa69f8e8d09b.png)

![изображение](https://user-images.githubusercontent.com/5559926/106449133-b0dad180-6494-11eb-8b46-d30feecc3b23.png)

**Comment by manuel489** [comment]
Thanks! Closing.
