### ISSUE TITLE
Acronyms horizontal separation -- OGC documents

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#62]
*In relation to https://github.com/metanorma/mn-native-pdf/issues/89*

In OGC documents, the separation between acronym and description is a little too long (in my opinion).

*PDF output:*
![issue4-pdf](https://user-images.githubusercontent.com/33627611/106398659-95b38780-63ea-11eb-9d77-f13221a3b01b.PNG)

*DOC output:*
![issue4-doc](https://user-images.githubusercontent.com/33627611/106398648-7caad680-63ea-11eb-8cab-e726d1d39116.PNG)

Can we match the horizontal separation to DOC output? (It's easier to read it in that way.)

**Comment by ronaldtse** [comment]
Agree that the DOC output looks a bit more reasonable.

**Comment by Intelligent2013** [comment]
Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/106485233-6f145000-64c1-11eb-9f0a-789e598500d6.png)

**Comment by manuel489** [comment]
Thanks!
