### ISSUE TITLE
MN -> PDF: Incorrect display of normative and bibliographic references in PDF BSI

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#77]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

From *bs-iso-30042*:

````
[bibliography]
== Normative references

[NOTE,type=boilerplate]
--
The following documents are referred to in the text in such a way that some or all of their content constitutes requirements of this document. For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.
--

* [[[iso_std_iso_8601_-1_en,ISO 8601-1]]], _Date and time — Representations for information interchange — Part 1: Basic rules_

* [[[iso_std_iso_8601_-2_en,ISO 8601-2]]], _Date and time — Representations for information interchange — Part 2: Extensions_

* [[[ISO_12620,ISO 12620]]], _Management of terminology resources — Data category specifications_

* [[[iso_std_iso_16642_en,ISO 16642]]], _Computer applications in terminology — Terminological markup framework_

* [[[iso_std_iso_21720_en_clause_XLIFFXMLLocalisationinterchangefileforma,ISO 21720]]], _XLIFF (XML Localisation interchange file format)_

* [[[iso_std_iso-iec_10646_en,ISO/IEC 10646]]], _Information technology — Universal Coded Character Set (UCS)_
````

Markup is correct, but not the output.

Output:
![issue2-generated](https://user-images.githubusercontent.com/33627611/127896929-385a91af-abb5-453f-b3bf-3bce99c738c6.PNG)

Original source:
![issue2-original](https://user-images.githubusercontent.com/33627611/127897011-588037a7-cfd4-4e87-beed-a1001d2cf43f.PNG)

**Comment by manuel489** [comment]
In addition, in Bibliography section:

From *bs-iso-30042*:
![issue3-generated](https://user-images.githubusercontent.com/33627611/127897717-5408abd4-2935-42bf-b707-e1d9e7d21ff3.PNG)

Comma should not be present.

**Comment by Intelligent2013** [comment]
1st issue fixed in https://github.com/metanorma/mn-native-pdf-bsi/commit/5c56bb0b145fccd0f8fa75ccf09447f6addd63e8
![image](https://user-images.githubusercontent.com/5559926/128075695-3acbeee4-6469-4151-ae86-4add5ef71a4e.png)


> Comma should not be present.

Fixed:
![image](https://user-images.githubusercontent.com/5559926/128075745-5e076597-5c39-4234-ba29-bb09bc725495.png)

**Comment by manuel489** [comment]
@Intelligent2013, in the first fix, a comma should be present after the standard identifier.
Like this:

![Capture1](https://user-images.githubusercontent.com/33627611/128611235-5c9866c4-375e-43f4-92c0-460a975bc9b4.PNG)

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/128705041-f91b4e86-c94c-424b-b372-783913f4dec3.png)

**Comment by manuel489** [comment]
Fix confirmed, thanks @Intelligent2013!
Closing.
