### ISSUE TITLE
MN -> PDF: Table footnotes not displaying well in BSI PDF

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#78]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

It seems that footnotes in tables are not showing up correctly.

From *bs-en-12973*:
````
[[tab_A.2]]
.Responsibility (●) and participation (X) during the phases of the VA/VE work plan  footnote:[The responsibility and participation will vary from project to project and from organization to organization.]
[cols="1848,1609,1790,1655,1549,1549",options="header,footer",width=641px]
|===
^| *Phase Name*
^| **Phase No.**
^| *Decision maker*
^| *Team leader or VA/VE project leader*
^| *Working group*
^| *Operational departments*

|Preliminary Phase ^|0 ^|● ^|  ^|  ^|X
|Project Definition ^|1 ^|● ^|X ^|  ^|X
|Planning ^|2 ^|  ^|● ^|  ^| 
|Gathering data ^|3 ^|  ^|● ^|X ^|X
|Function Analysis ^|4 ^|  ^|● ^|● ^|X
|Gathering Ideas ^|5 ^|  ^|● ^|● ^|X
|Evaluation of solutions ^|6 ^|  ^|X ^|X ^|●
|Development of proposals ^|7 ^|  ^|● ^|● ^|X
|Presentation of proposals ^|8 ^|● ^|● ^|● ^|X
|Implementation ^|9 ^|● ^|X ^|  ^|●

|===
````

Output:
![issue4-generated](https://user-images.githubusercontent.com/33627611/127950462-0d3a2a77-9640-4e39-bb61-c86c59eda51f.PNG)

(Notice that footnote content is shown twice at the caption area.)

Original:
![issue4-original](https://user-images.githubusercontent.com/33627611/127950451-5a151825-5bc4-48b5-9206-1faefca2d460.PNG)

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/128518686-6c8ae11d-5057-4d7b-a68e-2e144affb4b4.png)

**Comment by manuel489** [comment]
@Intelligent2013, I can't reproduce the same result of yours.
I'm using this command from `Makefile`:

````
pdf: 
	bundle exec metanorma -t bsi -x presentation $(adoc) && \
	java -Xss5m -Xmx2048m -jar mn2pdf/mn2pdf-1.35.jar -x $(dir $(adoc))/document.presentation.xml -s $(BSI_XSL) -o $(dir $(adoc))/document.pdf
````

In command line:
````
make pdf adoc=sources.mnconvert/adoptions/bs-en-12973/document.adoc
````

I see that you've edited a `common.xsl` file from `mn-native-pdf` repository.
How can I include this file in the PDF generation?

**Comment by Intelligent2013** [comment]
@manuel489 unfortunately sources.mnconvert/bsi.international-standard.xsl  updates automatically after any update in mnconvert repository, but not in mn-native-pdf. I'll try to fix it.
I've triggered mnconvert, so in sources.mnconvert/bsi.international-standard.xsl should be latest xslt now.

**Comment by manuel489** [comment]
Thanks @Intelligent2013 !
Fix confirmed, closing.
