### ISSUE TITLE
MN -> PDF: Perhaps blank sections are not correctly rendered in BSI

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#81]
* In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

Blank sections tend to be horizontally aligned with the first paragraph and
this does not happen in current PDF layout of BSI.
But since current layout is based on *bs-202000*, I'm not sure if this is
an intrinsic feature of it (because it doesn't include blank sections).

From *bs-en-iso-56000*:
![issue1-generated](https://user-images.githubusercontent.com/33627611/128614950-24fa1b32-6c4d-4589-baac-1d9a1309e7eb.PNG)

Original:
![issue1-original](https://user-images.githubusercontent.com/33627611/128614903-b12a16fe-1573-4eb7-a137-6062c7a49795.PNG)

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/128704666-add4d559-a9e0-4df3-bc75-3601f07153e7.png)

**Comment by manuel489** [comment]
Fix confirmed, thanks.
Closing.
