### ISSUE TITLE
MN -> PDF: Incomplete document identifier in BSI standard

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#83]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

Document identifier is incomplete in generated version.
In addition, there is a sole m-dash at the end of the main title.

From *pd-iso-tr-44000*:
![issue1-generated](https://user-images.githubusercontent.com/33627611/128637885-67c626d7-c7c5-405c-ac0f-8f4980d942bf.PNG)

Original:
![issue1-original](https://user-images.githubusercontent.com/33627611/128637889-73abbbdf-6d0d-4695-974d-f74e2e7ef0e1.PNG)

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/129251834-bff51de7-7f60-4986-b68f-d5d6f239aacb.png)

**Comment by manuel489** [comment]
Fix confirmed, closing.
