### ISSUE TITLE
MN -> PDF: Footnote font size too large in BSI layout?

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#84]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

I find that footnote font size is too large in BSI PDF layout.

From *bs-7858*:
![issue3-generated](https://user-images.githubusercontent.com/33627611/128644381-ec4efcf0-c448-459c-87ca-727d18c7cf83.PNG)

Notice that the font size is almost the same as main content.

Original:
![issue3-original](https://user-images.githubusercontent.com/33627611/128644384-1407d70a-b485-4cdb-b9a7-151d181149c0.PNG)

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/129053169-1951888b-b066-4a45-8f04-ffb25fe40085.png)

**Comment by manuel489** [comment]
Fix confirmed, closing.
Thanks!
