### ISSUE TITLE
MN -> PDF: Remove copyright symbol from document identifier

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#85]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

I'm not sure if the copyright symbol should be included in the document identifier.
It is not in original PDF.

From *bs-8887-1-2006*:
![issue5-generated](https://user-images.githubusercontent.com/33627611/128645151-f9ef16ee-b26c-4a5e-b504-661f329a2dc6.PNG)

Also in every page header:
![issue5_2-generated](https://user-images.githubusercontent.com/33627611/128645208-811251dc-09c4-418a-8216-33774d71e180.PNG)

**Comment by Intelligent2013** [comment]
Source STS XML, copyright sign in the element `copyright-year`:
```xml
<permissions>
<copyright-year>© 2006</copyright-year>
<copyright-holder>British Standards Institution</copyright-holder>
</permissions>
```

To do:
1. in xslt remove `©`
2. if `doc-number` ends with `:<copyright-year>`, then remove it.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/129062420-3442c2f2-9687-4a30-a999-ff9db4e241d6.png)

![image](https://user-images.githubusercontent.com/5559926/129062473-98d58fd3-57ae-4c16-a81e-a4b1facc2f60.png)

**Comment by manuel489** [comment]
Fix confirmed, closing.
