### ISSUE TITLE
MN -> PDF: Overlapping text in table caption

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#87]
*In relation https://github.com/metanorma/metanorma-bsi/issues/30*

From *bs-8500-2-2015-A2-2019*:
![issue6-generated](https://user-images.githubusercontent.com/33627611/129297171-55006f71-c8dd-483d-b555-c0c7bba90f21.PNG)
![issue6_2-generated](https://user-images.githubusercontent.com/33627611/129297266-b24f4817-02a0-4ee3-ac9d-0628018699c7.PNG)

**Comment by Intelligent2013** [comment]
This is Apache FOP limitation for the table's running header. It can't calculate running header row height depends on the text length. I have to move the table name from the header into the standalone block before table.

**Comment by Intelligent2013** [comment]
Done:

![image](https://user-images.githubusercontent.com/5559926/129590758-b92a6c5b-4596-4b62-8493-c5984c7b6bd1.png)

![image](https://user-images.githubusercontent.com/5559926/129590805-689d12ef-6bef-433a-a760-8cb70e8cd435.png)

**Comment by manuel489** [comment]
Fix confirmed, thanks @Intelligent2013!
Closing.
