### ISSUE TITLE
MN -> PDF: Missing comma in Bibliography references

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#91]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

In bibliography section, references must have a comma after the standard ID.

From *bs-202000*:
![issue2_1-generated](https://user-images.githubusercontent.com/33627611/130287527-56c931a3-d07b-4347-8431-6b3c0ffd404a.PNG)

It should be:

*ISO/TS 9002:2016, ...*

*ISO 10667-1, ...*

*ISO 10667-2, ...*

Like in Normative References:
![issue2_2-generated](https://user-images.githubusercontent.com/33627611/130287563-a0da38da-4cec-4e74-8e96-67b6e5ef3740.PNG)

**Comment by ronaldtse** [comment]
@manuel489 can you clarify whether this is only for BSI or for other flavors?

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/130318300-b37c876b-0d17-49e1-ad66-838388e1ee15.png)

**Comment by manuel489** [comment]
> @manuel489 can you clarify whether this is only for BSI or for other flavors?

@ronaldtse this is just for BSI flavor.

**Comment by manuel489** [comment]
@Intelligent2013 the comma issue is fixed, but now there is a duplicate *Standard publications* tittle:
![issue1-generated](https://user-images.githubusercontent.com/33627611/130359127-6c7c7278-225a-4bc4-ae81-313a98ddc50d.PNG)

The markup looks fine, and this issue is not showing up in other documents with similar markup.
So maybe it's a specific case.

**Comment by manuel489** [comment]
Issue above has been fixed. Closing.
