### ISSUE TITLE
Migrate GHA workflows to use Fontist

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf#94]
To replace these lines:

https://github.com/metanorma/mn2pdf/blob/9317c5aba0a526d2fe0fd4726fb020be87cdb02f/.github/workflows/release.yml#L25-L27

https://github.com/metanorma/mn2pdf/blob/9317c5aba0a526d2fe0fd4726fb020be87cdb02f/.github/workflows/macos.yml#L29-L34

https://github.com/metanorma/mn2pdf/blob/9317c5aba0a526d2fe0fd4726fb020be87cdb02f/.github/workflows/ubuntu.yml#L26-L32

**Comment by CAMOBAP** [comment]
Done
