### ISSUE TITLE
MN -> PDF: Annex sections should begin in a new page

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#98]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

I understand that annex sections must begin in a new page.

*From bs-iso-44001:*
![issue1-generated](https://user-images.githubusercontent.com/33627611/135558770-3c875b8e-56ef-4108-9415-60511fe72264.PNG)

**Comment by manuel489** [comment]
Well, apparently it's permitted in this layout. 

*From bs-202000 original source:*
![issue1-original](https://user-images.githubusercontent.com/33627611/135559517-6a42731c-14b3-4b2c-9b57-85a1c1730bd9.PNG)


@Intelligent2013, is it possible to workaround the case description above in the description though?

**Comment by Intelligent2013** [comment]
I think the issue in the title that splits across pages. Fixed:

![image](https://user-images.githubusercontent.com/5559926/135714903-5f36c32e-2ea3-460a-ac3e-fcbc27fb24b4.png)

**Comment by manuel489** [comment]
Confirmed fixed. Thanks @Intelligent2013 !
Closing.
